import { useEffect, useRef } from "react";
import useReducedMotion from "../hooks/useReducedMotion";

const VERTEX = `attribute vec2 position; void main(){gl_Position=vec4(position,0.0,1.0);}`;
const FRAGMENT = `precision mediump float; uniform vec2 resolution; uniform float time; uniform float scroll; uniform vec2 pointer; uniform float velocity; float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453123);} float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);} void main(){vec2 uv=gl_FragCoord.xy/resolution.xy;vec2 p=uv-.5;p.x*=resolution.x/resolution.y;float drift=time*.012+scroll*.9;float n=noise(p*3.0+drift)*.12+noise(p*7.0-drift*.7)*.045;float light=exp(-length(p-vec2(pointer.x*.08,pointer.y*.08+scroll*.08))*2.5);float horizon=smoothstep(.8,-.25,p.y);vec3 color=vec3(.035,.045,.04)+vec3(.34,.5,.12)*(light*.035+n*.2)+vec3(.18,.12,.07)*(horizon*.08);color+=velocity*.008*vec3(.34,.5,.12);gl_FragColor=vec4(color,1.0);}`;

export default function GlobalAtmosphere() {
  const canvasRef = useRef(null); const reduced = useReducedMotion();
  useEffect(() => {
    const canvas = canvasRef.current; const gl = canvas?.getContext("webgl", { alpha: false, antialias: false, powerPreference: "low-power" }); if (!gl) return;
    const shader = (type, source) => { const value = gl.createShader(type); gl.shaderSource(value, source); gl.compileShader(value); return value; };
    const program = gl.createProgram(); gl.attachShader(program, shader(gl.VERTEX_SHADER, VERTEX)); gl.attachShader(program, shader(gl.FRAGMENT_SHADER, FRAGMENT)); gl.linkProgram(program); gl.useProgram(program);
    const buffer = gl.createBuffer(); gl.bindBuffer(gl.ARRAY_BUFFER, buffer); gl.bufferData(gl.ARRAY_BUFFER, new Float32Array([-1,-1,1,-1,-1,1,1,1]), gl.STATIC_DRAW); const position = gl.getAttribLocation(program, "position"); gl.enableVertexAttribArray(position); gl.vertexAttribPointer(position, 2, gl.FLOAT, false, 0, 0);
    const u = Object.fromEntries(["resolution", "time", "scroll", "pointer", "velocity"].map((name) => [name, gl.getUniformLocation(program, name)])); let frame = 0, scroll = 0, targetScroll = 0, velocity = 0, targetVelocity = 0, focus = 0, px = 0, py = 0, tx = 0, ty = 0, lastScroll = 0;
    const resize = () => { const dpr = Math.min(devicePixelRatio || 1, reduced ? 1 : 1.5); canvas.width = innerWidth * dpr; canvas.height = innerHeight * dpr; canvas.style.width = `${innerWidth}px`; canvas.style.height = `${innerHeight}px`; gl.viewport(0, 0, canvas.width, canvas.height); }; const updateScroll = () => { const max = document.documentElement.scrollHeight - innerHeight; targetScroll = max > 0 ? scrollY / max : 0; targetVelocity = Math.min(Math.abs(scrollY - lastScroll) / 80, 1); lastScroll = scrollY; }; const pointer = (event) => { tx = event.clientX / innerWidth - .5; ty = event.clientY / innerHeight - .5; }; const focusTech = (event) => { focus = event.detail?.intensity || .22; }; const draw = (time) => { scroll += (targetScroll - scroll) * .045; velocity += (targetVelocity - velocity) * .08; targetVelocity *= .9; focus *= .94; px += (tx - px) * .045; py += (ty - py) * .045; gl.uniform2f(u.resolution, canvas.width, canvas.height); gl.uniform1f(u.time, reduced ? 0 : time / 1000); gl.uniform1f(u.scroll, scroll); gl.uniform2f(u.pointer, reduced ? 0 : px, reduced ? 0 : py); gl.uniform1f(u.velocity, reduced ? 0 : velocity + focus); gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4); frame = requestAnimationFrame(draw); }; resize(); updateScroll(); addEventListener("resize", resize); addEventListener("scroll", updateScroll, { passive: true }); addEventListener("pointermove", pointer, { passive: true }); addEventListener("tech-focus", focusTech); frame = requestAnimationFrame(draw); return () => { cancelAnimationFrame(frame); removeEventListener("resize", resize); removeEventListener("scroll", updateScroll); removeEventListener("pointermove", pointer); removeEventListener("tech-focus", focusTech); gl.deleteBuffer(buffer); gl.deleteProgram(program); };
  }, [reduced]);
  return <canvas ref={canvasRef} className="global-atmosphere" aria-hidden="true" />;
}
